import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Plus, Minus, Search, MessageCircle } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Link } from "react-router-dom";

const faqs = [
  {
    category: "General",
    items: [
      {
        question: "What is Novluma?",
        answer:
          "Novluma is an AI-powered content generation platform designed to help creators and businesses scale their content production. We use advanced LLMs (like Gemini 2.0) to write high-quality blog posts, social media captions, and emails in seconds.",
      },
      {
        question: "Is there a free trial?",
        answer:
          "Yes! every new account comes with a free starter plan that lets you generate up to 5,000 words. No credit card required to start.",
      },
      {
        question: "Can I use the content for commercial purposes?",
        answer:
          "Absolutely. You own 100% of the content generated by Novluma. You can use it for your business, your clients, or personal projects without restriction.",
      },
    ],
  },
  {
    category: "Billing & Plans",
    items: [
      {
        question: "How does the word count limit work?",
        answer:
          "Your word count resets every billing cycle (monthly). If you're on the Free plan, it's a lifetime limit. Pro plans get renewed quotas every month.",
      },
      {
        question: "Can I cancel anytime?",
        answer:
          "Yes, you can cancel your subscription at any time from your Dashboard settings. You'll keep access until the end of your current billing period.",
      },
    ],
  },
  {
    category: "Technical",
    items: [
      {
        question: "Which AI models do you use?",
        answer:
          "We primarily powered by Google's Gemini 2.0 Flash and Pro models. We automatically switch between models to ensure the best speed and quality for your specific task.",
      },
      {
        question: "Is my data secure?",
        answer:
          "Yes. We use industry-standard encryption for all data. Your project content is stored securely in Google Cloud (Firestore), and we do not share your personal data with third parties.",
      },
    ],
  },
];

const AccordionItem = ({
  question,
  answer,
  isOpen,
  onClick,
}: {
  question: string;
  answer: string;
  isOpen: boolean;
  onClick: () => void;
}) => {
  return (
    <div className="border-b border-gray-200 dark:border-gray-800 last:border-0">
      <button
        onClick={onClick}
        className="w-full flex items-center justify-between py-6 text-left group"
      >
        <span className="text-lg font-medium text-gray-900 dark:text-white group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors">
          {question}
        </span>
        <span
          className={`ml-4 flex-shrink-0 flex items-center justify-center w-8 h-8 rounded-full border transition-all duration-200 ${
            isOpen
              ? "bg-indigo-600 border-indigo-600 text-white rotate-180"
              : "border-gray-300 dark:border-gray-700 text-gray-400 group-hover:border-indigo-600 group-hover:text-indigo-600"
          }`}
        >
          {isOpen ? (
            <Minus className="w-4 h-4" />
          ) : (
            <Plus className="w-4 h-4" />
          )}
        </span>
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <p className="pb-6 text-gray-600 dark:text-gray-400 leading-relaxed max-w-3xl">
              {answer}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export function FAQPage() {
  const [openIndex, setOpenIndex] = useState<string | null>("General-0");
  const [searchQuery, setSearchQuery] = useState("");

  const toggleAccordion = (index: string) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const filteredFaqs = faqs
    .map((category) => ({
      ...category,
      items: category.items.filter(
        (item) =>
          item.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
          item.answer.toLowerCase().includes(searchQuery.toLowerCase())
      ),
    }))
    .filter((category) => category.items.length > 0);

  return (
    <div className="min-h-screen bg-white dark:bg-gray-950 text-gray-900 dark:text-gray-100 selection:bg-indigo-100 dark:selection:bg-indigo-900/30 selection:text-indigo-900 dark:selection:text-indigo-100 flex flex-col">
      <Navbar />

      <main className="flex-grow">
        {/* Hero Section - Matching Contact Page Design */}
        <section className="relative pt-32 pb-32 lg:pt-40 lg:pb-40 overflow-hidden bg-indigo-950 dark:bg-black">
          {/* Background Effects */}
          <div className="absolute inset-0 overflow-hidden">
            <div className="absolute -top-[40%] -left-[20%] w-[70%] h-[70%] rounded-full bg-indigo-900/20 dark:bg-indigo-900/40 blur-3xl"></div>
            <div className="absolute top-[20%] -right-[20%] w-[60%] h-[60%] rounded-full bg-indigo-800/20 dark:bg-indigo-800/30 blur-3xl"></div>
          </div>

          <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="text-center max-w-3xl mx-auto"
            >
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.2 }}
                className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-900/50 border border-indigo-800 text-indigo-300 text-sm font-medium mb-6"
              >
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-indigo-500"></span>
                </span>
                Support Center
              </motion.div>

              <h1 className="text-4xl md:text-6xl font-bold text-white mb-6 tracking-tight">
                Frequently Asked{" "}
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-cyan-400">
                  Questions
                </span>
              </h1>
              <p className="text-xl text-indigo-200 leading-relaxed max-w-2xl mx-auto">
                Everything you need to know about the product and billing. Can’t
                find the answer you’re looking for? Please chat to our friendly
                team.
              </p>
            </motion.div>
          </div>
        </section>

        {/* FAQ Content Section */}
        <section className="relative -mt-20 pb-24 z-20">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto">
              {/* Search Bar - Floating */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.3 }}
                className="bg-white dark:bg-gray-900 p-2 rounded-2xl shadow-xl border border-gray-100 dark:border-gray-800 mb-12 flex items-center"
              >
                <div className="relative w-full">
                  <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                  <Input
                    type="text"
                    placeholder="Search for answers (e.g., 'billing', 'api key')..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-12 py-6 text-lg bg-transparent border-none focus-visible:ring-0 shadow-none"
                  />
                </div>
              </motion.div>

              {/* FAQ Accordion */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.4 }}
                className="space-y-8"
              >
                {filteredFaqs.length > 0 ? (
                  filteredFaqs.map((category, catIndex) => (
                    <div key={catIndex}>
                      <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-6 flex items-center gap-2 px-2">
                        <span className="w-8 h-1 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-full"></span>
                        {category.category}
                      </h3>
                      <div className="bg-white dark:bg-gray-900/50 rounded-2xl border border-gray-100 dark:border-gray-800 p-2 md:p-8 shadow-sm">
                        {category.items.map((item, index) => {
                          const itemKey = `${category.category}-${index}`;
                          return (
                            <AccordionItem
                              key={index}
                              question={item.question}
                              answer={item.answer}
                              isOpen={openIndex === itemKey}
                              onClick={() => toggleAccordion(itemKey)}
                            />
                          );
                        })}
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="text-center py-12 bg-gray-50 dark:bg-gray-900 rounded-2xl">
                    <p className="text-gray-500 dark:text-gray-400">
                      No results found for "{searchQuery}"
                    </p>
                  </div>
                )}
              </motion.div>

              {/* Contact CTA */}
              <motion.div
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                viewport={{ once: true }}
                className="mt-24 text-center bg-gray-50 dark:bg-gray-900/50 p-12 rounded-3xl border border-gray-100 dark:border-gray-800"
              >
                <div className="w-16 h-16 bg-indigo-100 dark:bg-indigo-900/30 rounded-2xl flex items-center justify-center mx-auto mb-6">
                  <MessageCircle className="w-8 h-8 text-indigo-600 dark:text-indigo-400" />
                </div>
                <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                  Still have questions?
                </h3>
                <p className="text-gray-600 dark:text-gray-400 mb-8 max-w-lg mx-auto">
                  Can't find the answer you're looking for? Our team is here to
                  help you get back on track.
                </p>
                <div className="flex flex-col sm:flex-row justify-center gap-4">
                  <Link
                    to="/contact"
                    className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-3 rounded-xl font-medium transition-colors shadow-lg shadow-indigo-500/20"
                  >
                    Contact Support
                  </Link>
                  <a
                    href="mailto:support@novluma.com"
                    className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 hover:border-indigo-500 text-gray-900 dark:text-white px-8 py-3 rounded-xl font-medium transition-colors"
                  >
                    Email Us
                  </a>
                </div>
              </motion.div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}

export default FAQPage;
